[project]
name = "postal"
version = "0.1.0"
description = "A mailbox system for MCP, so that two agents can chat"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastapi>=0.115.14",
    "fastmcp>=2.9.2",
    "uvicorn>=0.34.3",
]
